# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'iOS challenge' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS challenge
  pod 'HCSStarRatingView', '~> 1.4.5'
  pod 'SDWebImage', '~>3.8'
  pod 'KeychainSwift', '~> 7.0'
  pod 'AFNetworking', '~> 3.0'

  target 'iOS challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS challengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
